# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/arunshankar/sba-1.6

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/arunshankar/sba-1.6

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arunshankar/sba-1.6/CMakeFiles /Users/arunshankar/sba-1.6/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/arunshankar/sba-1.6/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sba

# Build rule for target.
sba: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sba
.PHONY : sba

# fast build rule for target.
sba/fast:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/build
.PHONY : sba/fast

#=============================================================================
# Target rules for targets named eucsbademo

# Build rule for target.
eucsbademo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eucsbademo
.PHONY : eucsbademo

# fast build rule for target.
eucsbademo/fast:
	$(MAKE) -f demo/CMakeFiles/eucsbademo.dir/build.make demo/CMakeFiles/eucsbademo.dir/build
.PHONY : eucsbademo/fast

sba_chkjac.o: sba_chkjac.c.o

.PHONY : sba_chkjac.o

# target to build an object file
sba_chkjac.c.o:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/sba_chkjac.c.o
.PHONY : sba_chkjac.c.o

sba_chkjac.i: sba_chkjac.c.i

.PHONY : sba_chkjac.i

# target to preprocess a source file
sba_chkjac.c.i:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/sba_chkjac.c.i
.PHONY : sba_chkjac.c.i

sba_chkjac.s: sba_chkjac.c.s

.PHONY : sba_chkjac.s

# target to generate assembly for a file
sba_chkjac.c.s:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/sba_chkjac.c.s
.PHONY : sba_chkjac.c.s

sba_crsm.o: sba_crsm.c.o

.PHONY : sba_crsm.o

# target to build an object file
sba_crsm.c.o:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/sba_crsm.c.o
.PHONY : sba_crsm.c.o

sba_crsm.i: sba_crsm.c.i

.PHONY : sba_crsm.i

# target to preprocess a source file
sba_crsm.c.i:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/sba_crsm.c.i
.PHONY : sba_crsm.c.i

sba_crsm.s: sba_crsm.c.s

.PHONY : sba_crsm.s

# target to generate assembly for a file
sba_crsm.c.s:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/sba_crsm.c.s
.PHONY : sba_crsm.c.s

sba_lapack.o: sba_lapack.c.o

.PHONY : sba_lapack.o

# target to build an object file
sba_lapack.c.o:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/sba_lapack.c.o
.PHONY : sba_lapack.c.o

sba_lapack.i: sba_lapack.c.i

.PHONY : sba_lapack.i

# target to preprocess a source file
sba_lapack.c.i:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/sba_lapack.c.i
.PHONY : sba_lapack.c.i

sba_lapack.s: sba_lapack.c.s

.PHONY : sba_lapack.s

# target to generate assembly for a file
sba_lapack.c.s:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/sba_lapack.c.s
.PHONY : sba_lapack.c.s

sba_levmar.o: sba_levmar.c.o

.PHONY : sba_levmar.o

# target to build an object file
sba_levmar.c.o:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/sba_levmar.c.o
.PHONY : sba_levmar.c.o

sba_levmar.i: sba_levmar.c.i

.PHONY : sba_levmar.i

# target to preprocess a source file
sba_levmar.c.i:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/sba_levmar.c.i
.PHONY : sba_levmar.c.i

sba_levmar.s: sba_levmar.c.s

.PHONY : sba_levmar.s

# target to generate assembly for a file
sba_levmar.c.s:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/sba_levmar.c.s
.PHONY : sba_levmar.c.s

sba_levmar_wrap.o: sba_levmar_wrap.c.o

.PHONY : sba_levmar_wrap.o

# target to build an object file
sba_levmar_wrap.c.o:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/sba_levmar_wrap.c.o
.PHONY : sba_levmar_wrap.c.o

sba_levmar_wrap.i: sba_levmar_wrap.c.i

.PHONY : sba_levmar_wrap.i

# target to preprocess a source file
sba_levmar_wrap.c.i:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/sba_levmar_wrap.c.i
.PHONY : sba_levmar_wrap.c.i

sba_levmar_wrap.s: sba_levmar_wrap.c.s

.PHONY : sba_levmar_wrap.s

# target to generate assembly for a file
sba_levmar_wrap.c.s:
	$(MAKE) -f CMakeFiles/sba.dir/build.make CMakeFiles/sba.dir/sba_levmar_wrap.c.s
.PHONY : sba_levmar_wrap.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sba"
	@echo "... eucsbademo"
	@echo "... sba_chkjac.o"
	@echo "... sba_chkjac.i"
	@echo "... sba_chkjac.s"
	@echo "... sba_crsm.o"
	@echo "... sba_crsm.i"
	@echo "... sba_crsm.s"
	@echo "... sba_lapack.o"
	@echo "... sba_lapack.i"
	@echo "... sba_lapack.s"
	@echo "... sba_levmar.o"
	@echo "... sba_levmar.i"
	@echo "... sba_levmar.s"
	@echo "... sba_levmar_wrap.o"
	@echo "... sba_levmar_wrap.i"
	@echo "... sba_levmar_wrap.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

